# Generated by Django 4.1 on 2023-11-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('position', models.CharField(default='', max_length=100, null=True)),
                ('device_sn', models.CharField(default='', max_length=100, null=True)),
                ('device_vendor', models.CharField(default='', max_length=100, null=True)),
                ('device_type', models.CharField(default='', max_length=100, null=True)),
                ('device_working_hours', models.CharField(default='', max_length=100, null=True)),
                ('cpu_used', models.FloatField(default=0, null=True)),
                ('remain_mem', models.FloatField(default=0, null=True)),
                ('remain_harddisk', models.FloatField(default=0, null=True)),
                ('network_speed', models.FloatField(default=0, null=True)),
                ('os', models.CharField(default='', max_length=100, null=True)),
                ('mac', models.CharField(default='', max_length=80, null=True)),
                ('update_time', models.CharField(default='', max_length=50, null=True)),
                ('productionline_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AssetDeviceInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20)),
                ('device_sn', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_id', models.IntegerField(default=0)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('name', models.CharField(default='', max_length=45, null=True)),
                ('state', models.CharField(default='', max_length=10, null=True)),
                ('product', models.CharField(default='', max_length=45, null=True)),
                ('version', models.CharField(default='', max_length=45, null=True)),
                ('cpe', models.CharField(default='', max_length=100, null=True)),
                ('extrainfo', models.CharField(default='', max_length=60, null=True)),
                ('update_time', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JtopoDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=200)),
                ('imgUrl', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JtopoFilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topo_id', models.CharField(max_length=100)),
                ('topo_src', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Productionline',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortened', models.CharField(default='', max_length=50)),
                ('workshop_id', models.IntegerField(default=0)),
                ('asset_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortened', models.CharField(default='', max_length=50)),
                ('productionline_number', models.IntegerField(default=0)),
            ],
        ),
    ]
