# Generated by Django 4.1 on 2023-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cpu_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_vendor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_working_hours',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='asset',
            name='network_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='remain_harddisk',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='remain_mem',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assetservice',
            name='cpe',
            field=models.CharField(default='', max_length=100),
        ),
    ]
